version: "3.9"
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - PORT=3001
    depends_on:
      - db
  db:
    container_name: lab-6-mariadb
    image: mariadb:latest
    
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: lab_6
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
  phpmyadmin:
    container_name: lab-6-phpmyadmin
    image: arm64v8/phpmyadmin:latest
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
volumes:
  db-data:
